version: "3"

tasks:
  default:
    desc: Run all checks (format, vet, build, test)
    cmds:
      - task: install-hooks
      - task: check

  install-hooks:
    desc: Install git pre-commit hook
    cmds:
      - chmod +x .git/hooks/pre-commit

  install-tools:
    desc: Install development tools
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  build:
    desc: Build the library
    cmds:
      - go build ./...

  test:
    desc: Run tests with race detector and coverage
    cmds:
      - go test -v -race -coverprofile=coverage.out ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  lint:
    desc: Run golangci-lint
    deps:
      - install-tools
    cmds:
      - golangci-lint run ./...

  check:
    desc: Run all checks (format, vet, build, test)
    cmds:
      - task: fmt
      - task: lint
      - task: vet
      - task: build
      - task: test

  clean:
    desc: Clean build artifacts
    cmds:
      - go clean ./...
      - rm -f coverage.out
