version: "3"

tasks:
  default:
    desc: Run all checks (format, vet, build, test)
    cmds:
      - task: install-hooks
      - task: check

  install-hooks:
    desc: Install git pre-commit hook
    cmds:
      - chmod +x .git/hooks/pre-commit

  build:
    desc: Build the library and binaries
    cmds:
      - task: build-lib
      - task: build-decoder
      - task: build-encoder

  build-lib:
    desc: Build the library
    cmds:
      - go build ./...

  build-decoder:
    desc: Build the decoder binary
    cmds:
      - go build -o .bin/decoder ./cmd/decoder

  build-encoder:
    desc: Build the encoder binary
    cmds:
      - go build -o .bin/encoder ./cmd/encoder

  test:
    desc: Run tests with race detector and coverage
    cmds:
      - go test -v -race -coverprofile=coverage.out ./...

  harness:
    desc: Run toml-test
    deps:
      - build-encoder
      - build-decoder
    cmds:
      - go tool toml-test test -toml 1.1 -decoder=.bin/decoder -encoder=.bin/encoder

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  lint:
    desc: Run golangci-lint
    cmds:
      - go tool golangci-lint run ./...

  check:
    desc: Run all checks (format, vet, build, test)
    cmds:
      - task: test
      - task: fmt
      - task: lint
      - task: vet
      - task: build-lib
      - task: harness

  clean:
    desc: Clean build artifacts
    cmds:
      - go clean ./...
      - rm -rf coverage.out .bin
